name: "Run Make test"

run-name: "Run Make test for PR: ${{ github.event.pull_request.title }}"

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  minishell-test:
    runs-on: ubuntu-slim
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install dependencies (readline / build-essential / pkg-config)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libreadline-dev \
            build-essential \
            pkg-config \
            cmake \
            g++

      - name: Run Make test
        run: make test
