name: "Run Make test"

run-name: "Run Make test for PR: ${{ github.event.pull_request.title }}"

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  minishell-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Install dependencies (build-essential / pkg-config)
        run: |
          sudo apt-get update
          sudo apt-get install -y \


      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Install readline
        run: brew install readline

      - name: Run Make test
        run: make test
